### ISSUE TITLE
FTBFS: in gtk-layer-shell-0

### ISSUE THREAD

**Issue by mcepl** [ilyazzz/sway-marker#1]
Command ``cargo build --release`` ends with:
```
   Compiling gtk-layer-shell-sys v0.2.0
error: failed to run custom build command for `gtk-layer-shell-sys v0.2.0`

Caused by:
  process didn't exit successfully: `/home/matej/archiv/knihovna/repos/tmp/sway-marker/target/release/build/gtk-layer-shell-sys-c07fa2b5d4ec3513/build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=GTK_LAYER_SHELL_0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=GTK_LAYER_SHELL_0_STATIC
  cargo:rerun-if-env-changed=GTK_LAYER_SHELL_0_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  `"pkg-config" "--libs" "--cflags" "gtk-layer-shell-0" "gtk-layer-shell-0 >= 0.1"` did not exit successfully: exit code: 1
  --- stderr
  Package gtk-layer-shell-0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gtk-layer-shell-0.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'gtk-layer-shell-0', required by 'virtual:world', not found
  Package 'gtk-layer-shell-0', required by 'virtual:world', not found

warning: build failed, waiting for other jobs to finish...
error: build failed
```
[Complete build log](https://github.com/ilyazzz/sway-marker/files/6290123/cargo-build-release-log.txt)

Also, technical question … is this sway dependent, wouldn't it work with another Wayland compatible window manager/compositor? Shouldn't it be ``wl-marker``. Otherwise, the idea seems intriguing.

**Comment by ilya-zlobintsev** [comment]
Yes, this is sway dependent because it uses sway's ipc to create marks, with marks being a sway-specific feature in the first place (ignoring i3).

As for the build error, you need gtk-layer-shell installed. On arch this is the `gtk-layer-shell` package, other distros may split dev files into a separate package.

**Comment by ilya-zlobintsev** [comment]
I have created a [release](https://github.com/ilyazzz/sway-marker/releases/tag/0.1) with a pre-compiled binary if you have issues with compiling

**Comment by mcepl** [comment]
> As for the build error, you need gtk-layer-shell installed. On arch this is the `gtk-layer-shell` package, other distros may split dev files into a separate package.

Then it would be lovely to mention it in README?

**Comment by ilya-zlobintsev** [comment]
It already is:
>Compiling: install rust, gtk and gtk-layer-shell and build with `cargo build --release`

**Comment by mcepl** [comment]
Oh sorry, I missed that.

I wanted as a repentance to create openSUSE package of sway-marker (https://build.opensuse.org/package/show/home:mcepl:work/sway-marker), but I cannot send it to the distribution, because you don't have a license. Please, add it and some license file.

**Comment by ilya-zlobintsev** [comment]
Done.

**Comment by mcepl** [comment]
Thank you. *Pro futuro* it is a good habit to actually add that license message from the end of GPL to every source file.
