### ISSUE TITLE
Automatically applying marks to all windows at once?

### ISSUE THREAD

**Issue by markstos** [ilyazzz/sway-marker#5]
Hello,

This is a nice little project.  The code is very easy to follow and is a good "Hello World" example of how to draw basic windows on Wayland with Rust.

I was wondering if you've considered an approach for switching windows like [wmfocus](https://github.com/svenstaro/wmfocus).

In that model, there's no need to mark a window in advance of switching to it. Instead, when you activate the tool, every visible window gets a visible label applied.  All the labels are displayed on the screen, you type and then switch to it.

There are a couple reasons why this tool might have a more interesting take on the idea:

 * wmfocus doesn't support Wayland
 * wmfocus uses transient labels, not persistent marks.  If Sway marks were assigned to windows, that would open some new options: 
    * Sway has the option to display marks in title bars, so there's a persistent visual clue about what mark is assigned
    * If you remember one the automatically assigned marks, you could skip using the tool and instead use a direct keybinding that means, for example, "Focus window with mark B".

**Comment by ilya-zlobintsev** [comment]
I think this is an interesting idea, the navigation reminds me of vim navigation plugins for web browsers. It is however a non-trivial design to implement, as there would be a lot of things to do:
- A background service running to mark windows automatically (theoretically windows could be marked on application startup, but then you wouldn't see them until you try to navigate to one)
- An option to draw the marks over windows (personally I use sway with titlebars disabled, so there would be no way to see labels in such a scenario without an overlay)

This would be a lot more than what sway-marker currently does (a simple popup to create and navigate to marks), and would be more of a "reimplement wmfocus for sway" project. 

You should also take a look at [swayr](https://sr.ht/~tsdh/swayr/). I'm not entirely sure if it supports the kind of marking that you're describing, but it does have quite a lot of options for window navigation, and it is a much better fit for the task of automatically marking windows in the background.

With that said, I would be willing to add integration of other tools into sway-marker. For example, if swayr would mark windows in the background, sway-marker could show hints on what marks already exist. Though at this point, as you said, sway-marker may not be needed already.

**Comment by markstos** [comment]
Thanks for considering this. I'll consider if  swayr might help here and also consider patching wmfocus to work better with Sway.
